"""HubSpot Leads API v1 client module for lead management, search, and lifecycle operations.

This module provides the LeadsClient class for interacting with HubSpot's
Leads API, supporting lead CRUD operations, search with flexible filtering
and sorting, webhook callback management, and lead lifecycle transitions
(close/open).

Key Exports:
    LeadsClient: Domain client for the Leads API, inheriting from
        BaseClient (hapi/base.py) for HTTP transport.
    list_to_dict_with_python_case_keys: Utility function that builds
        bidirectional lookup dicts mapping both camelCase and snake_case
        option name variants to their canonical camelCase API key.
    SORT_OPTIONS: List of valid sort field names for lead queries.
    TIME_PIVOT_OPTIONS: List of valid time pivot field names.
    SEARCH_OPTIONS: List of all recognized search/filter parameter names.
    BOOLEAN_SEARCH_OPTIONS: Set of search options that accept boolean values.

Architecture Note:
    The module implements a camelCase <-> snake_case option conversion
    layer that allows callers to use Pythonic snake_case parameter names
    (e.g., 'time_pivot', 'email_opt_out') which are transparently
    converted to the camelCase format expected by the HubSpot API
    (e.g., 'timePivot', 'emailOptOut'). This conversion is performed
    via pre-computed lookup dictionaries built at module load time by
    list_to_dict_with_python_case_keys.

See Also:
    hapi.base.BaseClient: Core HTTP engine that handles authentication,
        retry logic, and response parsing for all API calls.
    hapi.error.HapiError: Exception hierarchy for API error responses.
"""
import time
from base import BaseClient
import logging_helper
#from pprint import pprint
 


LEADS_API_VERSION = '1'

def list_to_dict_with_python_case_keys(list_):
    """Build a bidirectional lookup dict mapping camelCase and snake_case option names.

    For each option name string in the input list, this function creates
    dictionary entries that map both the original camelCase form and a
    generated snake_case variant back to the original camelCase key. This
    enables callers to use either naming convention when specifying API
    parameters.

    The conversion algorithm for each item:
        1. The original camelCase string maps to itself.
        2. If the string contains uppercase characters, a snake_case
           variant is generated by lowering the first character and
           inserting an underscore before each subsequent uppercase
           character (e.g., 'timePivot' -> 'time_pivot').
        3. The snake_case variant also maps to the original camelCase key.

    Args:
        list_ (list): A list of camelCase option name strings to index.
            Each string represents a valid API parameter name.

    Returns:
        dict: A dictionary where keys are both the original camelCase
            names and their generated snake_case equivalents, and values
            are always the original camelCase key string. For items
            that are already all-lowercase, only the identity mapping
            is included.
    """
    d = {}
    for item in list_:
        d[item] = item
        if item.lower() != item:
            python_variant = item[0].lower() + ''.join([c if c.lower()==c else '_%s'%c.lower() for c in item[1:]])
            d[python_variant] = item
    return d

SORT_OPTIONS = [
    'firstName',
    'lastName',
    'email',
    'address',
    'phone',
    'insertedAt',
    'fce.convertDate',
    'lce.convertDate',
    'lastModifiedAt',
    'closedAt']
SORT_OPTIONS_DICT = list_to_dict_with_python_case_keys(SORT_OPTIONS)
TIME_PIVOT_OPTIONS = [
    'insertedAt',
    'firstConvertedAt',
    'lastConvertedAt',
    'lastModifiedAt',
    'closedAt']
TIME_PIVOT_OPTIONS_DICT = list_to_dict_with_python_case_keys(TIME_PIVOT_OPTIONS)
SEARCH_OPTIONS = [
    'search',
    'sort', 
    'dir',
    'max',
    'offset',
    'startTime',
    'stopTime',
    'timePivot',
    'excludeConversionEvents',
    'emailOptOut',
    'eligibleForEmail',
    'bounced',
    'isNotImported']
SEARCH_OPTIONS_DICT = list_to_dict_with_python_case_keys(SEARCH_OPTIONS)
BOOLEAN_SEARCH_OPTIONS = set([
    'excludeConversionEvents',
    'emailOptOut',
    'eligibleForEmail',
    'bounced',
    'isNotImported'])

MAX_BATCH=100

class LeadsClient(BaseClient):
    """Client for HubSpot Leads API v1 providing lead CRUD, search, webhook, and lifecycle operations.

    LeadsClient provides a Pythonic interface to HubSpot's Leads API,
    supporting lead retrieval (single and batch), search with flexible
    filtering and sorting, lead registration via forms, field updates,
    webhook callback management, and lead lifecycle transitions
    (close/open).

    All endpoints route through the leads/v{version}/ subpath, where
    version defaults to '1' and can be overridden via the 'version'
    key in extra_options passed to the constructor.

    Endpoint Access Overview:
        Base URL pattern: /leads/v1/{resource}
        Authentication: API key as query parameter or OAuth access token,
            injected by BaseClient._prepare_request_auth().
        Response format: JSON parsed to Python dicts/lists by
            BaseClient._digest_result().

    The client implements a camelCase search option conversion layer
    (via camelcase_search_options) that allows callers to pass
    Pythonic snake_case parameter names which are transparently
    converted to the camelCase format expected by the HubSpot API.

    Attributes:
        log (logging.Logger): Named logger ('hapi.leads') configured
            via logging_helper for API call tracing and diagnostics.

    Example:
        client = LeadsClient(api_key='demo')
        leads = client.get_leads(sort='last_name', dir='asc')
    """

    def __init__(self, *args, **kwargs):
        """Initialize the Leads client with authentication and configure logging.

        Delegates all authentication and connection setup to
        BaseClient.__init__, then creates a named logger instance
        for lead-specific API call tracing.

        Args:
            *args: Positional arguments passed through to
                BaseClient.__init__ (typically api_key).
            **kwargs: Keyword arguments passed through to
                BaseClient.__init__ (e.g., timeout, access_token,
                refresh_token, client_id, mixins).
        """
        super(LeadsClient, self).__init__(*args, **kwargs)
        self.log = logging_helper.get_log('hapi.leads')

    # Why: [Assumptions Made] — The snake_case to camelCase conversion assumes
    # that the HubSpot API expects camelCase parameter names while Python
    # convention uses snake_case. This mapping layer lets callers use Pythonic
    # parameter names (e.g., 'time_pivot') which are transparently converted
    # to API-expected format ('timePivot'). The SEARCH_OPTIONS_DICT,
    # SORT_OPTIONS_DICT, and TIME_PIVOT_OPTIONS_DICT are pre-computed at
    # module load time to avoid repeated conversion overhead.
    def camelcase_search_options(self, options):
        """Convert Python snake_case search options to HubSpot camelCase API parameters.

        Translates a dictionary of search/filter options from Pythonic
        snake_case keys to the camelCase format expected by the HubSpot
        Leads API. The conversion handles three distinct paths:

        1. Option keys: All keys are looked up in SEARCH_OPTIONS_DICT
           to find their camelCase equivalent (e.g., 'time_pivot' ->
           'timePivot'). Unrecognized keys pass through unchanged.
        2. Sort values: When the key resolves to 'sort', the value
           is also converted via SORT_OPTIONS_DICT (e.g.,
           'last_name' -> 'lastName').
        3. Time pivot values: When the key resolves to 'timePivot',
           the value is converted via TIME_PIVOT_OPTIONS_DICT.
        4. Boolean options: When the resolved key is in
           BOOLEAN_SEARCH_OPTIONS, the value is lowercased to a
           string representation ('true'/'false').

        Args:
            options (dict): Search parameters with possible snake_case
                keys and values. May include sort, filter, pagination,
                and boolean flag options.

        Returns:
            dict: A new dictionary with all keys and applicable values
                converted to the camelCase format expected by the
                HubSpot API.
        """
        new_options = {}
        for key in options:
            value = options[key]
            new_key = SEARCH_OPTIONS_DICT.get(key, key)
            if new_key == 'sort':
                value = SORT_OPTIONS_DICT.get(value, value)
            elif new_key == 'timePivot':
                value = TIME_PIVOT_OPTIONS_DICT.get(value, value)
            elif new_key in BOOLEAN_SEARCH_OPTIONS:
                value = str(value).lower()
            new_options[new_key] = value
        return new_options

    def _get_path(self, subpath):
        """Construct the versioned API path for a leads endpoint.

        Builds the URL path segment by combining the leads API prefix
        with a configurable version number and the provided subpath.

        Args:
            subpath (str): The endpoint-specific path segment to append
                after the versioned prefix (e.g., 'list/', 'lead/abc123').

        Returns:
            str: The full API path in the format 'leads/v{version}/{subpath}',
                where version defaults to '1' from LEADS_API_VERSION if not
                overridden in self.options.
        """
        return 'leads/v%s/%s' % (self.options.get('version') or LEADS_API_VERSION, subpath)
  
    def get_lead(self, guid, **options):
        """Retrieve a single lead by its GUID.

        Convenience wrapper that delegates to get_leads and returns
        only the first result. This issues the same batch-style API
        call as get_leads but extracts the single lead record.

        Endpoint Access:
            HTTP Method: GET
            URL: /leads/v1/list/?guids[0]={guid}
            Auth: API key or OAuth token via BaseClient.
            Response: JSON list of lead dicts; first element returned.

        Args:
            guid (str): The unique identifier of the lead to retrieve.
            **options: Additional search/filter options passed through
                to get_leads and then to the API as query parameters.

        Returns:
            dict: The lead data dictionary for the requested GUID.

        Raises:
            HapiError: When the API returns a non-2xx status code.
            IndexError: When no leads match the provided GUID,
                resulting in an empty list from get_leads.
        """
        return self.get_leads(guid, **options)[0]

    def get_leads(self, *guids, **options):
        """Retrieve leads by GUIDs and/or search with filter options.

        Dual-purpose method that can fetch specific leads by GUID or
        search the leads database with flexible filter, sort, and
        pagination options. When GUIDs are provided, they are sent as
        indexed query parameters (guids[0], guids[1], etc.). All
        options are run through camelcase_search_options to convert
        Pythonic snake_case names to API-expected camelCase format.

        Endpoint Access:
            HTTP Method: GET
            URL: /leads/v1/list/?guids[0]={guid0}&guids[1]={guid1}&...
                plus any search/filter/sort query parameters.
            Auth: API key or OAuth token via BaseClient.
            Body: None (GET request).
            Response: JSON list of lead data dictionaries.

        Args:
            *guids (str): Variable number of lead GUID strings to
                retrieve. When omitted, the method performs a search
                using only the filter/sort options.
            **options: Search, sort, filter, and pagination options.
                Supports both camelCase and snake_case keys (e.g.,
                'timePivot' or 'time_pivot'). Recognized options
                include: search, sort, dir, max, offset, startTime,
                stopTime, timePivot, excludeConversionEvents,
                emailOptOut, eligibleForEmail, bounced, isNotImported.

        Returns:
            list: A list of lead data dictionaries from the API.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        original_options = options
        options = self.camelcase_search_options(options.copy())
        params = {}
        for i in xrange(len(guids)):
            params['guids[%s]'%i] = guids[i]
        for k in options.keys():
            if k in SEARCH_OPTIONS:
                params[k] = options[k]
                del options[k]
        leads = self._call('list/', params, **options)
        self.log.info("retrieved %s leads through API ( %soptions=%s )" % 
                (len(leads), guids and 'guids=%s, '%guids or '', original_options))
        return leads

    # Why: [Trade-offs] — The blanket try/except returning {'guid': '-1'} as a sentinel
    # value is a deliberate fault-tolerance decision. The method silently swallows ALL
    # exceptions (including network errors, auth failures, and server errors) and returns
    # a predictable fallback object. This prevents callers from needing error handling
    # for lead lookups that may legitimately fail (e.g., deleted leads), but it hides
    # genuine errors. The '-1' guid serves as a null-object pattern that callers can
    # check without try/except.
    def retrieve_lead(self, *guid, **options):
        """Retrieve a single lead by GUID with silent error fallback.

        Fetch a lead record from the API, wrapping the call in a
        blanket exception handler that returns a sentinel value on
        ANY failure. Unlike get_lead, this method never raises
        exceptions — it always returns a dict, either containing
        the real lead data or a fallback with guid='-1'.

        IMPORTANT: This method silently swallows all exceptions,
        including network errors, authentication failures, and
        server errors. Callers should check the returned dict's
        'guid' field for '-1' to detect lookup failures.

        Endpoint Access:
            HTTP Method: GET
            URL: /leads/v1/lead/{guid}
            Auth: API key or OAuth token via BaseClient.
            Body: None (GET request).
            Response: JSON lead data dict, or sentinel on error.

        Args:
            *guid (str): The lead GUID to retrieve. Passed as a
                variable-length argument; the value is used directly
                in the URL path segment.
            **options: Additional options passed through to the
                underlying _call method as query parameters.

        Returns:
            dict: The lead data dictionary on success, or
                {'guid': '-1'} sentinel dict on any error.
        """
        cur_guid = guid or '' 
        params = {}
        for key in options:
            params[key] = options[key]
        """ Set guid to -1 as default for not finding a user """
        lead = {'guid' : '-1'}
        """ wrap lead call so that it doesn't error out when not finding a lead """
        try:
            lead = self._call('lead/%s' % cur_guid, params, **options)
        except:
            """ no lead here """
        return lead


    def update_lead(self, guid, update_data=None, **options):
        """Update a lead's fields by GUID.

        Send a PUT request to update the specified lead with the
        provided field data. The lead's GUID is automatically
        injected into the update_data dict before transmission,
        ensuring the API receives the target identifier in the
        request body.

        Endpoint Access:
            HTTP Method: PUT
            URL: /leads/v1/lead/{guid}/
            Auth: API key or OAuth token via BaseClient.
            Body: JSON-encoded dict containing 'guid' and all
                fields to update.
            Response: JSON dict with the updated lead data.

        Args:
            guid (str): The unique identifier of the lead to update.
            update_data (dict or None): Dictionary of lead fields to
                update. If None, an empty dict is used. The 'guid'
                key is automatically added/overwritten with the
                provided guid parameter.
            **options: Additional options passed through to the
                underlying _call method.

        Returns:
            dict: The API response containing updated lead data.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        update_data = update_data or {}
        update_data['guid'] = guid
        return self._call('lead/%s/' % guid, data=update_data, method='PUT', **options)
    
    # Why: [Trade-offs] — The original developer comment (#WTF are these 2 methods
    # for?) is preserved as-is. These webhook methods (get_webhook, register_webhook)
    # provide callback URL management for lead notifications, allowing external systems
    # to receive lead change events via webhook callbacks.
    def get_webhook(self, **options):  #WTF are these 2 methods for?
        """Retrieve the currently registered webhook callback URL.

        Fetch the callback URL configuration for lead event
        notifications. This endpoint returns the URL that HubSpot
        will POST lead change events to.

        Endpoint Access:
            HTTP Method: GET
            URL: /leads/v1/callback-url
            Auth: API key or OAuth token via BaseClient.
            Body: None (GET request).
            Response: JSON dict containing callback URL configuration.

        Args:
            **options: Additional options passed through to the
                underlying _call method.

        Returns:
            dict: The callback URL configuration from the API.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        return self._call('callback-url', **options)
    
    def register_webhook(self, url, **options):
        """Register a webhook callback URL for lead event notifications.

        Configure HubSpot to send lead change event notifications
        to the specified URL. The URL is sent as both a query
        parameter and in the POST body to satisfy the API contract.

        Endpoint Access:
            HTTP Method: POST
            URL: /leads/v1/callback-url?url={url}
            Auth: API key or OAuth token via BaseClient.
            Body: Form/JSON data containing {'url': url}.
            Response: JSON dict confirming registration.

        Args:
            url (str): The callback URL that HubSpot should POST
                lead event notifications to.
            **options: Additional options passed through to the
                underlying _call method.

        Returns:
            dict: The API response confirming webhook registration.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        return self._call('callback-url', params={'url': url}, data={'url': url}, method='POST', **options)
    
    # Why: [Assumptions Made] — The closedAt field uses epoch milliseconds
    # (int(time.time()*1000)) matching HubSpot's Java-style timestamp convention.
    # The update_lead helper is reused to set this field, treating lead closure as
    # a regular field update rather than a dedicated API endpoint. The isNotImported
    # field is NOT set here despite being a boolean search option, suggesting closure
    # doesn't affect import status.
    def close_lead(self, guid, close_time=None, **options):
        """Close a lead by setting its closedAt timestamp.

        Mark a lead as closed by updating its closedAt field with
        the provided timestamp or the current time. Delegates to
        update_lead, treating closure as a regular field update.

        Endpoint Access:
            HTTP Method: PUT (via update_lead)
            URL: /leads/v1/lead/{guid}/
            Auth: API key or OAuth token via BaseClient.
            Body: JSON-encoded dict with 'guid' and 'closedAt'
                fields, where closedAt is epoch milliseconds.
            Response: JSON dict with the updated lead data.

        Args:
            guid (str): The unique identifier of the lead to close.
            close_time (int or None): The closure timestamp as epoch
                milliseconds. If None, defaults to the current time
                in milliseconds (int(time.time() * 1000)).
            **options: Additional options passed through to
                update_lead and the underlying _call method.

        Returns:
            dict: The API response from update_lead containing
                updated lead data with the closedAt field set.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        return self.update_lead(guid, {'closedAt': close_time or int(time.time()*1000)}, **options)
    
    # Why: [Trade-offs] — open_lead does not return the result of update_lead
    # (missing return statement), which differs from close_lead's behavior. This
    # appears to be an oversight but is preserved for backward compatibility.
    def open_lead(self, guid, **options):
        """Reopen a previously closed lead by clearing its closedAt field.

        Mark a lead as open by setting its closedAt field to an
        empty string, effectively removing the closure timestamp.
        Delegates to update_lead for the field update.

        Note: This method does NOT return the result of update_lead
        due to a missing return statement. This differs from
        close_lead's behavior but is preserved for backward
        compatibility.

        Endpoint Access:
            HTTP Method: PUT (via update_lead)
            URL: /leads/v1/lead/{guid}/
            Auth: API key or OAuth token via BaseClient.
            Body: JSON-encoded dict with 'guid' and 'closedAt'
                set to empty string as the reopen mechanism.
            Response: JSON dict (not returned to caller).

        Args:
            guid (str): The unique identifier of the lead to reopen.
            **options: Additional options passed through to
                update_lead and the underlying _call method.

        Returns:
            None: This method does not return a value despite
                update_lead returning the API response.

        Raises:
            HapiError: When the API returns a non-2xx status code.
        """
        self.update_lead(guid, {'closedAt': ''}, **options)
